ALTER PROCEDURE dw.stpAtualizaDimAnoCenso AS 
BEGIN
	DROP TABLE IF EXISTS #Anos
	CREATE TABLE #Anos (Anos INT)

	INSERT INTO #Anos
	SELECT DISTINCT NU_ANO_CENSO FROM 
	(
	SELECT DISTINCT NU_ANO_CENSO 
	FROM stg.MICRODADOS_CADASTRO_CURSOS WITH(NOLOCK)

	UNION ALL 

	SELECT DISTINCT NU_ANO_CENSO 
	FROM stg.MICRODADOS_CADASTRO_CURSOS WITH(NOLOCK)
	) a

	TRUNCATE TABLE dw.DimAnoCenso
	INSERT INTO dw.DimAnoCenso
	SELECT * FROM #Anos ORDER BY 1
END


CREATE PROCEDURE dw.AtualizaDimCurso AS 
BEGIN
	
	SELECT DISTINCT 
		NU_ANO_CENSO,
		NO_CURSO,
		CO_CURSO
		NO_CINE_AREA_GERAL,
		NO_CINE_AREA_ESPECIFICA,
		NO_CINE_AREA_DETALHADA,
		TP_GRAU_ACADEMICO,
		TP_NIVEL_ACADEMICO,
		TP_MODALIDADE_ENSINO,
		IN_GRATUITO
	FROM stg.MICRODADOS_CADASTRO_CURSOS WITH(NOLOCK)


END